### ISSUE TITLE
OEFrame.paint(Graphics) is throwing a NullPointerException

### ISSUE THREAD

**Issue by Tripazzy** [Tripazzy/JOSOE#2]
This method is throwing a NullPointerException:

    @Override
    public void paint(Graphics g) {
        g.fillRect(getX(), getY(), getWidth(), 30); //<- This is causing the error
        
        draw(g);
    }

If you want to take a look, it's in the [OEFrame](https://github.com/Tripazzy/JOSOE/blob/master/src/salsaboy/josoe/ui/OEFrame.java) class

**Comment by TheOnlyMrCat** [comment]
Where is *g* assigned?
It's throwing a NullPointerException because *g == null*

**Comment by TheOnlyMrCat** [comment]
I found the answer in [this post](https://coderanch.com/t/407987/java/getGraphics-returns-null). You're trying to get the graphics of the JFrame before it is visible.
