### ISSUE TITLE
Should this be maximized?

### ISSUE THREAD

**Issue by Tripazzy** [Tripazzy/JOSOE#7]
/**
     * The method to run when it is unminimized.
     * @param reason The reason it was unminimized.
     */
    void onMaximize(int reason);

Should this be maximized or shown? Because maximized is covering the whole screen, isn't it?

**Comment by TheOnlyMrCat** [comment]
Here "maximized" is used as "anti-minimized". And yes, maximized does mean covering the entire screen.
